name: s2pipe

services:
    media:
        profiles: ["all", "node"]
        restart: unless-stopped
        init: true
        stop_grace_period: 20s
        shm_size: '2gb'
        build:
            context: .
            dockerfile: docker/Dockerfile.media
        ports:
            - "${MEDIA_ICE_PORT}:${MEDIA_ICE_PORT}/udp"
        privileged: true
        volumes:
            - /dev:/dev
        environment:
            MEDIA_ICE_IP: ${MEDIA_ICE_IP}
            MEDIA_ICE_PORT: ${MEDIA_ICE_PORT}
            CAPTURE_SOURCE: ${CAPTURE_SOURCE}
            CAPTURE_DEVICE: ${CAPTURE_DEVICE}
            CAPTURE_AUDIO: ${CAPTURE_AUDIO}
            AUDIO_BUFFER_TIME: ${AUDIO_BUFFER_TIME:-20000}
            AUDIO_PERIOD_TIME: ${AUDIO_PERIOD_TIME:-5000}
            AUDIO_FRAME_DURATION: ${AUDIO_FRAME_DURATION:-10}
            CAPTURE_FORMAT: ${CAPTURE_FORMAT}
            CAPTURE_WIDTH: ${CAPTURE_WIDTH}
            CAPTURE_HEIGHT: ${CAPTURE_HEIGHT}
            CAPTURE_FPS: ${CAPTURE_FPS}

    node:
        profiles: ["all", "node"]
        restart: unless-stopped
        depends_on:
            - media
        stop_grace_period: 10s
        build:
            context: .
            dockerfile: docker/Dockerfile.node
        ports:
            - "${NODE_PORT}:${NODE_PORT}"
        privileged: true
        volumes:
            - /dev:/dev
        environment:
            NODE_PORT: ${NODE_PORT}
            MEDIA_HOST: media
            CAPTURE_SOURCE: ${CAPTURE_SOURCE}
            PICO_SERIAL: ${PICO_SERIAL}
            ENABLE_BT_WAKE: ${ENABLE_BT_WAKE:-true}
            SWITCH_BT_MAC: ${SWITCH_BT_MAC:-}
            CONTROLLER_BT_MAC: ${CONTROLLER_BT_MAC:-}
            CONTROLLER_BT_PID: ${CONTROLLER_BT_PID:-}
            PLAYER_PIN: ${PLAYER_PIN:-}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
            TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY:-}

    client:
        profiles: ["all", "client"]
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile.client
        ports:
            - "${CLIENT_PORT}:${CLIENT_PORT}"
        environment:
            CLIENT_PORT: ${CLIENT_PORT}
            NODE_PORT: ${NODE_PORT}
            NODE_BASE_URL: ${NODE_BASE_URL}
            TURNSTILE_SITE_KEY: ${TURNSTILE_SITE_KEY:-}
